---
dist: xenial
language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev
    - nightly

install:
  - pip install tox tox-travis

script:
  - tox
