- name: Set version specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Install packages
  yum:
    name: "{{ network_packages | default([]) }}"
    state: present

- name: Enable network service
  service:
    name: "{{ network_service_name }}"
    state: started
    enabled: yes

- name: Configure networking connection profiles
  network_connections:
      provider:       "{{ network.provider    | default(network_provider) | mandatory }}"
      ignore_errors:  "{{ network.ignore_errors | default(omit) }} "
      connections:    "{{ network.connections | default([]) }}"

- name: Re-test connectivity
  ping:
